.TH "IPOL tools User Manual" 1 "03 Feb 2018" "IPOL documentation"

.SH NAME
nlmeans

.SH DESCRIPTION
Non local means denoising.

.SH SYNOPSIS
nlmeans input sigma output

.SH OPTIONS
.TP
input
name input graphics file (jpeg | png | tiff)
.TP
sigma
noise std (int, mandatory, recomended = 16)
.TP
output
name output graphics file (jpeg | png | tiff)

.SH EXAMPLE
nlmeans noisy.tiff 16 denoised.png

.SH COPYRIGHT
Copyright : (C) 2017 IPOL Image Processing On Line http://www.ipol.im/
 Licence   : GPL v3+, see GPLv3.txt

.SH SEE ALSO
 cjpeg (1),
 djpeg (1)

.SH CONTACTS
.TP
Author:
Nicola Pierazzo <nicolapierazzo@gmail.com>
.TP
Author:
Gabriele Facciolo <gfacciol@gmail.com>
.TP
Latest version available at:
https://github.com/npd/nlmeans
